-- Auto-generated by scripts/seed-templates.mjs
-- Paste into Supabase SQL Editor and run.
-- Safe to re-run: DELETEs existing is_starter=true rows first.

DELETE FROM public.routine_templates WHERE is_starter = true;

INSERT INTO public.routine_templates (name, description, category, difficulty, estimated_duration_minutes, exercises, is_starter)
VALUES (
  'StrongLifts A',
  NULL,
  'full_body',
  'beginner',
  45,
  '[{"exercise_id":"barbell-full-squat","sets":5,"reps":"5","rest_seconds":180,"order":0},{"exercise_id":"barbell-bench-press---medium-grip","sets":5,"reps":"5","rest_seconds":180,"order":1},{"exercise_id":"bent-over-barbell-row","sets":5,"reps":"5","rest_seconds":180,"order":2}]'::jsonb,
  true
);

INSERT INTO public.routine_templates (name, description, category, difficulty, estimated_duration_minutes, exercises, is_starter)
VALUES (
  'StrongLifts B',
  NULL,
  'full_body',
  'beginner',
  45,
  '[{"exercise_id":"barbell-full-squat","sets":5,"reps":"5","rest_seconds":180,"order":0},{"exercise_id":"standing-military-press","sets":5,"reps":"5","rest_seconds":180,"order":1},{"exercise_id":"barbell-deadlift","sets":1,"reps":"5","rest_seconds":300,"order":2}]'::jsonb,
  true
);

INSERT INTO public.routine_templates (name, description, category, difficulty, estimated_duration_minutes, exercises, is_starter)
VALUES (
  'Classic Push (PPL)',
  NULL,
  'push',
  'intermediate',
  60,
  '[{"exercise_id":"barbell-bench-press---medium-grip","sets":4,"reps":"6-8","rest_seconds":180,"order":0},{"exercise_id":"standing-military-press","sets":3,"reps":"6-8","rest_seconds":150,"order":1},{"exercise_id":"incline-dumbbell-press","sets":3,"reps":"8-12","rest_seconds":120,"order":2},{"exercise_id":"side-lateral-raise","sets":3,"reps":"10-12","rest_seconds":90,"order":3},{"exercise_id":"triceps-pushdown","sets":3,"reps":"10-12","rest_seconds":90,"order":4},{"exercise_id":"tricep-dumbbell-kickback","sets":3,"reps":"10-12","rest_seconds":90,"order":5}]'::jsonb,
  true
);

INSERT INTO public.routine_templates (name, description, category, difficulty, estimated_duration_minutes, exercises, is_starter)
VALUES (
  'Classic Pull (PPL)',
  NULL,
  'pull',
  'intermediate',
  60,
  '[{"exercise_id":"barbell-deadlift","sets":4,"reps":"5","rest_seconds":180,"order":0},{"exercise_id":"pullups","sets":3,"reps":"8-12","rest_seconds":150,"order":1},{"exercise_id":"bent-over-barbell-row","sets":4,"reps":"6-8","rest_seconds":150,"order":2},{"exercise_id":"seated-cable-rows","sets":3,"reps":"8-12","rest_seconds":90,"order":3},{"exercise_id":"face-pull","sets":3,"reps":"12-15","rest_seconds":60,"order":4},{"exercise_id":"barbell-curl","sets":3,"reps":"8-12","rest_seconds":90,"order":5}]'::jsonb,
  true
);

INSERT INTO public.routine_templates (name, description, category, difficulty, estimated_duration_minutes, exercises, is_starter)
VALUES (
  'Classic Legs (PPL)',
  NULL,
  'legs',
  'intermediate',
  70,
  '[{"exercise_id":"barbell-full-squat","sets":4,"reps":"6-8","rest_seconds":180,"order":0},{"exercise_id":"romanian-deadlift","sets":3,"reps":"8-10","rest_seconds":150,"order":1},{"exercise_id":"leg-press","sets":3,"reps":"10-12","rest_seconds":120,"order":2},{"exercise_id":"seated-leg-curl","sets":3,"reps":"10-12","rest_seconds":90,"order":3},{"exercise_id":"standing-calf-raises","sets":4,"reps":"10-15","rest_seconds":60,"order":4}]'::jsonb,
  true
);

INSERT INTO public.routine_templates (name, description, category, difficulty, estimated_duration_minutes, exercises, is_starter)
VALUES (
  '5/3/1 Upper',
  NULL,
  'upper',
  'intermediate',
  55,
  '[{"exercise_id":"barbell-bench-press---medium-grip","sets":3,"reps":"5","rest_seconds":180,"order":0,"notes":"Heavy working set (80-90% 1RM)"},{"exercise_id":"barbell-bench-press---medium-grip","sets":5,"reps":"10","rest_seconds":90,"order":1,"notes":"BBB volume set (50-60% 1RM)"},{"exercise_id":"bent-over-two-dumbbell-row","sets":5,"reps":"10","rest_seconds":90,"order":2},{"exercise_id":"face-pull","sets":3,"reps":"15","rest_seconds":60,"order":3}]'::jsonb,
  true
);

INSERT INTO public.routine_templates (name, description, category, difficulty, estimated_duration_minutes, exercises, is_starter)
VALUES (
  '5/3/1 Lower',
  NULL,
  'lower',
  'intermediate',
  60,
  '[{"exercise_id":"barbell-full-squat","sets":3,"reps":"5","rest_seconds":180,"order":0,"notes":"Heavy working set (80-90% 1RM)"},{"exercise_id":"barbell-full-squat","sets":5,"reps":"10","rest_seconds":90,"order":1,"notes":"BBB volume set (50-60% 1RM)"},{"exercise_id":"romanian-deadlift","sets":5,"reps":"10","rest_seconds":90,"order":2},{"exercise_id":"standing-calf-raises","sets":3,"reps":"15","rest_seconds":60,"order":3}]'::jsonb,
  true
);

INSERT INTO public.routine_templates (name, description, category, difficulty, estimated_duration_minutes, exercises, is_starter)
VALUES (
  'Core Circuit',
  NULL,
  'core',
  'beginner',
  20,
  '[{"exercise_id":"plank","sets":3,"reps":"45s","rest_seconds":45,"order":0},{"exercise_id":"cross-body-crunch","sets":3,"reps":"20","rest_seconds":45,"order":1},{"exercise_id":"russian-twist","sets":3,"reps":"20","rest_seconds":45,"order":2},{"exercise_id":"hanging-leg-raise","sets":3,"reps":"12","rest_seconds":45,"order":3}]'::jsonb,
  true
);
